services:
    nginx:
        image: nginx
        container_name: estoque-ms-nginx-container
        ports:
            - 8080:80
        networks:
            - soat-estoque-ms-net
        hostname: estoque-ms-nginx-hostname
        restart: on-failure:3
        volumes:
            - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./application:/var/www/html
        depends_on:
            microservice:
                condition: service_started

    microservice:
        container_name: estoque-ms-container
        hostname: estoque-ms-hostname
        build:
            context: .
            dockerfile: ./images/php/Dockerfile
        volumes:
            - ./application:/var/www/html
        restart: on-failure:3
        expose:
            - 9000
        networks:
            - soat-estoque-ms-net
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:17.5
        container_name: estoque-ms-postgres-container
        restart: always
        ports:
            - 5433:5432
        env_file:
            - ./containers/postgres/env/.env.dev
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - soat-estoque-ms-net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 5s

volumes:
    pgdata:

networks:
    soat-estoque-ms-net:
        name: soat-estoque-ms-net
        driver: bridge
